name: main

on:
  repository_dispatch:
    types: 
      - webhook-one
      - webhook-two

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello
      run: echo "Hello, I've been triggered by a webhook!"
    - name: Event Name
      run: |
        echo "Event triggered by $GITHUB_EVENT_NAME"
        echo "Dispatch type ${{ github.event.action }}"
        echo "${{ github.event.client-payload.version }}"
    - name: Goodbye
      if: ${{ github.event.action == 'webhook-one' }}
      run: npx cowsay "Bye!"
    - name: Adiós
      if: ${{ github.event.action == 'webhook-two' }}
      run: npx cowsay "Adiós!"
