name: test_wf_dispatch

run-name: ${{ github.workflow }}_${{ inputs.clickhouse_version }}_${{ inputs.id || github.run_number }}

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'UUID that can correct understand start'
        required: true
        type: string
      clickhouse_version:
        description: 'Clickhouse version'
        required: true
        type: string

jobs:
  print-clickhouse_version:
    runs-on: ubuntu-latest
    env:
      NEED_SETUP: true
    steps:
      - name: Check the input tag to ${{ inputs.clickhouse_version }}
        continue-on-error: true
        run: |
          docker manifest inspect chtools/test-clickhouse:${{ inputs.clickhouse_version }}
          echo "NEED_SETUP=false" >> $GITHUB_ENV
      - name: Test
        if: ${{ env.NEED_SETUP }}
        run: |
          echo NEXT_STEP
      - name: Last step
        run: echo Finish
