name: test_wf_dispatch

run-name: ${{ github.workflow }}_${{ inputs.clickhouse_version }}_${{ inputs.id || github.run_number }}

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'UUID that can correct understand start'
        required: true
        type: string
      clickhouse_version:
        description: 'Clickhouse version'
        required: true
        type: string

jobs:
  print-clickhouse_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check the input tag to ${{ inputs.clickhouse_version }} 
        run: |
          echo  The tags are ${{ inputs.clickhouse_version }}
          echo "SERVER_IP='$(hostname -I | awk '{print $1}')'" > $GITHub_ENV
      - name: read var
        run: |
          echo "Calling var from env using env context: server ip is ${{ env.SERVER_IP }}"
          echo "Calling var from env: server ip is $SERVER_IP"
