name: test_wf_dispatch

run-name: ${{ github.workflow }}_${{ inputs.clickhouse_version }}_${{ inputs.id || github.run_number }}

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'UUID that can correct understand start'
        required: true
        type: string
      clickhouse_version:
        description: 'Clickhouse version'
        required: true
        type: string

jobs:
  print-clickhouse_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check the input tag to ${{ inputs.clickhouse_version }} 
        run: |
          echo  The tags are ${{ inputs.clickhouse_version }}
          docker manifest inspect chtools/test-clickhouse: ${{ inputs.clickhouse_version }} > /dev/null 2>&1
          exit_code=$?        
          if [ $exit_code -eq 0 ]; then
            echo "VERSION_EXIST=true" >> $GITHub_ENV
          else
            echo "VERSION_EXIST=false" >> $GITHub_ENV
          fi
      - name: Print
        run: echo ${{ env.VERSION_EXIST }}
