name: test_wf_dispatch

run-name: ${{ inputs.prefix }}_${{github.workflow}}_${{ inputs.uuid }}

on:
  workflow_dispatch:
    inputs:
      run_prefix:
        description: 'Prefix runtime workflow'
        required: true
        type: string
      id:
        description: 'UUID that can correct understand start'
        required: true
        type: string
      clickhouse_version:
        description: 'Clickhouse version'
        required: true
        type: string

jobs:
  print-clickhouse_version:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to ${{ inputs.clickhouse_version }} 
        run: echo  The tags are ${{ inputs.clickhouse_version }} 
